.TH TTYRECGENERATOR 1 2018\-08\-11
.SH NAME

.B ttyrecgenerator:
Remove innecesary files or directories with a date and time pattern in the current directory.
.SH SYNOPSIS

ttyrecgenerator [\-h] [\-\-version] (\-\-create_example | \-\-remove | \-\-pretend)
                        [\-\-pattern PATTERN] [\-\-disable_log]
                        [\-\-remove_mode {RemainFirstInMonth,RemainLastInMonth}]
                        [\-\-too_young_to_delete TOO_YOUNG_TO_DELETE]
                        [\-\-max_files_to_store MAX_FILES_TO_STORE]
.SH DESCRIPTION

.PP
This app has the following mandatory parameters:
.PP
.RS
.B \-\-create_example
.RE
.PP
.RS
.RS
Create two directories called 'example' and 'example_directories' in the current working directory and fill it with example files with date and time patterns.
.RE
.RE
